preload = /usr/share/backgrounds/archlinux/awesome.png
wallpaper = HDMI-A-1,/usr/share/backgrounds/archlinux/awesome.png
wallpaper = DP-1,/usr/share/backgrounds/archlinux/awesome.png
wallpaper = DP-2,/usr/share/backgrounds/archlinux/awesome.png
splash = false
